export const MENU_MODE_CHANGE_REQUESTED = 'MENU_MODE_CHANGE_REQUESTED'

export const HTS_TRADE_INFO_REQUESTED = 'HTS_TRADE_INFO_REQUESTED'
export const HTS_TRADE_INFO_SUCCESS = 'HTS_TRADE_INFO_SUCCESS'
export const HTS_TRADE_INFO_FAILED = 'HTS_TRADE_INFO_FAILED'
