export const MAIL_VALUE_CHANGE_REQUESTED = 'MAIL_VALUE_CHANGE_REQUESTED'
export const NAME_VALUE_CHANGE_REQUESTED = 'NAME_VALUE_CHANGE_REQUESTED'
export const PWD_VALUE_CHANGE_REQUESTED = 'PWD_VALUE_CHANGE_REQUESTED'
export const PWD_CHECK_VALUE_CHANGE_REQUESTED = 'PWD_CHECK_VALUE_CHANGE_REQUESTED'

export const SIGN_UP_REQUESTED = 'SIGN_UP_REQUESTED'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const SIGN_UP_RESET = 'SIGN_UP_RESET'

export const MAIL_DUPLICATION_CHECK_SUCCESS = 'MAIL_DUPLICATION_CHECK_SUCCESS'
export const MAIL_DUPLICATION_CHECK_FAILED = 'MAIL_DUPLICATION_CHECK_FAILED'

export const SIGN_IN_REQUESTED = 'SIGN_IN_REQUESTED'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const SIGN_REDUCER_RESET = 'SIGN_REDUCER_RESET'
