export const HTS_TRADE_INFO_REQUESTED = 'HTS_TRADE_INFO_REQUESTED'
export const HTS_TRADE_INFO_SUCCESS = 'HTS_TRADE_INFO_SUCCESS'
export const HTS_TRADE_INFO_FAILED = 'HTS_TRADE_INFO_FAILED'

export const HTS_TRADE_ORDER_REQUESTED = 'HTS_TRADE_ORDER_REQUESTED'
export const HTS_TRADE_ORDER_SUCCESS = 'HTS_TRADE_ORDER_SUCCESS'
export const HTS_TRADE_ORDER_FAILED = 'HTS_TRADE_ORDER_FAILED'

export const HTS_API_KEY_REQUESTED = 'HTS_API_KEY_REQUESTED'
export const HTS_API_KEY_SUCCESS = 'HTS_API_KEY_SUCCESS'
export const HTS_API_KEY_FAILED = 'HTS_API_KEY_FAILED'
export const HTS_API_KEY_RESET = 'HTS_API_KEY_RESET'
export const HTS_API_KEY_STATE_CHANGE = 'HTS_API_KEY_STATE_CHANGE'

export const HTS_MARKET_INFO_REQUESTED = 'HTS_MARKET_INFO_REQUESTED'
export const HTS_MARKET_INFO_SUCCESS = 'HTS_MARKET_INFO_SUCCESS'
export const HTS_MARKET_INFO_FAILED = 'HTS_MARKET_INFO_FAILED'

export const HTS_MONEYTRAY_UNIT_CHANGE = 'HTS_MONEYTRAY_UNIT_CHANGE'

export const HTS_STD_UNIT_CHANGE = 'HTS_STD_UNIT_CHANGE'

export const HTS_ASSETS_REQUESTED = 'HTS_ASSETS_REQUESTED'
export const HTS_ASSETS_SUCCESS = 'HTS_ASSETS_SUCCESS'
export const HTS_ASSETS_FAILED = 'HTS_ASSETS_FAILED'

export const HTS_EXCHANGE_UPDATE = 'HTS_EXCHANGE_UPDATE'

export const HTS_MANAGES_REQUESTED = 'HTS_MANAGES_REQUESTED'
export const HTS_MANAGES_SUCCESS = 'HTS_MANAGES_SUCCESS'
export const HTS_MANAGES_FAILED = 'HTS_MANAGES_FAILED'
