export const HTS_TRADE_INFO_REQUESTED = 'HTS_TRADE_INFO_REQUESTED'
export const HTS_TRADE_INFO_SUCCESS = 'HTS_TRADE_INFO_SUCCESS'
export const HTS_TRADE_INFO_FAILED = 'HTS_TRADE_INFO_FAILED'

export const HTS_TRADE_ORDER_REQUESTED = 'HTS_TRADE_ORDER_REQUESTED'
export const HTS_TRADE_ORDER_SUCCESS = 'HTS_TRADE_ORDER_SUCCESS'
export const HTS_TRADE_ORDER_FAILED = 'HTS_TRADE_ORDER_FAILED'

export const HTS_API_KEY_REQUESTED = 'HTS_API_KEY_REQUESTED'
export const HTS_API_KEY_SUCCESS = 'HTS_API_KEY_SUCCESS'
export const HTS_API_KEY_FAILED = 'HTS_API_KEY_FAILED'
export const HTS_API_KEY_RESET = 'HTS_API_KEY_RESET'
export const HTS_API_KEY_STATE_CHANGE = 'HTS_API_KEY_STATE_CHANGE'
