xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["ec2-52-78-128-79.ap-northeast-2.compute.amazonaws.com:9200", "ec2-52-79-149-94.ap-northeast-2.compute.amazonaws.com:9200", "ec2-13-125-5-159.ap-northeast-2.compute.amazonaws.com:9200"]
xpack.monitoring.elasticsearch.username: "moebius"
xpack.monitoring.elasticsearch.password: "highbal1!"