stream:
  real-time:
    source-topic: "moebius.trade.upbit"
    output-topic: "moebius.trade.upbit.aggs.1m"
    flush-interval-ms: 10000
    application-id: "moebius-stream"
    aggregation-interval-minutes: 1