
spring:
  kafka:
    streams:
      application-id: moebius-streams
      bootstrap-servers: kafka.hashmainpro.com:9092
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
    jaas:
      enabled: true
      login-module: org.apache.kafka.common.security.plain.PlainLoginModule
      options:
        username: moebius
        password: VVbRzWYK4OHE
    bootstrap-servers: kafka.hashmainpro.com:9092

#      properties:
#        jass:
#          login-module: org.apache.kafka.common.security.plain.PlainLoginModule
server:
  port: 8081
#

stream:
  source.topic: "moebius.trade.upbit"
  output.topic: "trade-stats"